
jobs:
  include:
    - stage: build
      os: linux
      language: python
      python: "3.7"
      compiler:
        - clang
        - gcc
      install: 
        - pip install conan
        - apt install cmake
      script:
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
        - conan remote list
        - mkdir build && cd build && cmake --configure .. -DCMAKE_BUILD_TYPE=debug && cmake --build .
        - ctest --verbose .
    - stage: build
      os: osx
      language: shell
      install:
        - brew install python # install python3
        - pip install conan # install conan
        - brew install cmake
        - cmake --version
        - conan --version
      script:
        - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
        - conan remote list
        - mkdir build && cd build && cmake --configure .. -DCMAKE_BUILD_TYPE=debug && cmake --build .
        - ctest --verbose .
