os: linux
language: python
python: "3.7"

compiler:
  - gcc
  - clang
  
install:
  - pip install conan
  
script:
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
  - conan remote list
  - mkdir build && cd build && cmake --configure .. -DCMAKE_BUILD_TYPE=debug && cmake --build .
  - ctest .

compiler:
- clang
- gcc
