language: cpp

addons:
  apt:
    packages: 
      - python3
      - python3-pip
      - python3-setuptools
      - python3-wheel

before_script:
  - pip3 install --user conan

env:
  global:
    - CONAN_PATH=/home/${USER}/.local/bin/conan

compiler:
- clang
- gcc

script:
  - mkdir build && cd build && cmake --configure .. -DCMAKE_BUILD_TYPE=debug && cmake --build .
