language: cpp

addons:
  apt:
    packages: 
      - python3
      - python3-pip

before_script:
  - pip3 install --user conan

env:
  global:
    - CONAN_PATH=/home/${USER}/.local/bin/conan

compiler:
- clang
- gcc
