image:
  - Visual Studio 2017
clone_folder: c:\projects\source

install:
  - ps: >-
      echo "Downloading conan..."
      set PATH=%PATH%;%PYTHON%/Scripts/
      python -m pip install -q --upgrade pip
      pip.exe install -q conan
      conan user
      conan --version

build_script:
  - ps: >-
      mkdir build
      cd build
      cmake c:\projects\source -G "Visual Studio 15"
      cmake --build . --config "Debug"
    
test_script:
  - ps: ctest -C Debug
