image:
  - Visual Studio 2019

clone_folder: c:\projects\source

install:
  - cmd: >-
      echo "Downloading conan..."
            
      python --version
      
      REM choco install python3
      
      pip --version
      
      python -m pip install -U pip
      
      pip --version
      
      pip install -q conan
      
      conan user
      
      conan --version

build_script:
  - cmd: >-
      mkdir build
      
      cd build
      
      cmake c:\projects\source -G "Visual Studio 15"
      
      cmake --build . --config "Debug"
    
test_script:
  - cmd: ctest -C Debug
