image:
  - Visual Studio 2017
clone_folder: c:\projects\source

install:
  - cmd: >-
      echo "Downloading conan..."
      
      # choco install python3 --pre
      
      pip.exe install -q conan
      
      conan user
      
      conan --version

build_script:
  - cmd: >-
      mkdir build
      
      cd build
      
      cmake c:\projects\source -G "Visual Studio 15"
      
      cmake --build . --config "Debug"
    
test_script:
  - cmd: ctest -C Debug
